### ISSUE TITLE
Quick Start Forecast Error

### ISSUE THREAD

**Issue by hinsonl** [microsoft/finnts#83] opened 2021-11-13 17:12 UTC
Received the following error when running the forecast_time_series function in the Quick Start.

-- Refitting Individual Models 
Data is not ordered by the 'date_var'. Resamples will be arranged by `Date`.
Overlapping Timestamps Detected. Processing overlapping time series together using sliding windows.
Error: `...` is not empty.

We detected these problematic arguments:
* `ind`
* `class`

These dots only exist to allow future extensions and should be empty.
Did you misspecify an argument?
Run `rlang::last_error()` to see where the error occurred.

**Comment by mitokic** [comment] 2021-11-15 16:03
Hey @hinsonl, thanks for reaching out. This was caused by a package dependency (rsample) changing its function arguments. 

This has been fixed in the latest finnts commit. Please reinstall and try again.

**Closed** 2021-11-15 16:03 UTC
Labels: bug
